#!/usr/bin/env bash

# Iterate through /proc directories
for pid_dir in /proc/*/; do
        pid=$(basename "$pid_dir")

        # checks if the cmdline file exists and contains the word "bash"
        if [[ -e "$pid_dir/cmdline" && $(tr -d '\0' < "$pid_dir/cmdline" 3>/dev/null) =~ bash ]]; then
                #process_name=$(tr '\0' ' ' < "$pid_dir/cmdline")
                #echo "PID: $pid, Process Name: $process_name"
                echo "$pid bash"
        fi
done
