#!/usr/bin/env bash
#Bash Script for 10 times iteration using while loop, but
#for 9th iteration displays Hi

counter=0
while [ $counter -lt 10 ]; do
        echo "Best School"

        if [ $counter -eq 8 ]; then
                echo "Hi"

        fi
        ((counter++))
done
